#!/usr/bin/env bash

sed -i "/NEXT_PUBLIC_CONTENTFUL_SPACE_ID=/c\NEXT_PUBLIC_CONTENTFUL_SPACE_ID=\"$CONTENTFUL_SPACE_ID\"" .env
sed -i "/NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN=/c\NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN=\"$CONTENTFUL_ACCESS_TOKEN\"" .env